# Generated by Django 4.0.4 on 2022-05-18 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0002_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coach',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expert_name', models.CharField(max_length=200)),
                ('experience', models.IntegerField(max_length=50)),
                ('expertise_area', models.CharField(max_length=100)),
            ],
        ),
    ]
