# Generated by Django 4.0.4 on 2022-05-18 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0003_coach'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coach',
            name='experience',
            field=models.IntegerField(),
        ),
    ]
