# Generated by Django 4.0.4 on 2022-05-25 11:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0004_alter_coach_experience'),
    ]

    operations = [
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('food_item', models.CharField(max_length=100)),
                ('fat', models.IntegerField()),
                ('carb', models.IntegerField()),
                ('protein', models.IntegerField()),
                ('calories', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='UserDiet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('breakfast_quantity', models.IntegerField()),
                ('lunch_quantity', models.IntegerField()),
                ('dinner_quantity', models.IntegerField()),
                ('water', models.IntegerField()),
                ('total_calories', models.BigIntegerField()),
                ('breakfast_food', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='breakfast', to='register.food')),
                ('dinner_food', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='dinner', to='register.food')),
                ('lunch_food', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='lunch', to='register.food')),
                ('user_diet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_diet', to='register.person')),
            ],
        ),
    ]
